eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
name:
  value: lhw
spring:
  cloud:
    config:
      override-system-properties: false