spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vlad250608_
    url: jdbc:mysql://localhost:3306/lethimwatchdb
#      show-sql: true
server:
  port: 8082