spring:
    config:
        import: optional:configserver:http://localhost:8880
    application:
        name: user-service

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Vlad250608_
        url: jdbc:mysql://localhost:3306/lethimwatchdb
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect